version: '6'
services:
  app:
    container_name: psm-payroll-backend
    build: .
    ports: 
      - 8000:8000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres


  fullstack-postgres:
    image: postgres:latest
    container_name: psm-payroll-postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5000:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.10.0.2

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
# default network psm-payroll-network
networks:
  default :
    external: true
    name: psm-payroll-network